---
# tasks file for ansible-percona-server
#Install repo

- name: Add percona repository key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 8507EFA5
    state: present

- name: Add percona repository
  apt_repository:
    repo: 'deb http://repo.percona.com/apt {{ ansible_distribution_release }} main'
    state: present

- name: Add percona source repository
  apt_repository:
    repo: 'deb-src http://repo.percona.com/apt {{ ansible_distribution_release }} main'
    state: present

- name: Update apt cache
  apt: update_cache=yes

#Specify MySQL password before install. Needed because auth_socket is used for default installation
- name: Specify MySQL root password before installing
  debconf: name='percona-server-server-{{ db_version }}' question='percona-server-server-{{ db_version }}/root_password' value='{{ mysql_root_password | quote }}' vtype='password'

- name: Confirm MySQL root password before installing
  debconf: name='percona-server-server-{{ db_version }}' question='percona-server-server-{{ db_version }}/root_password_again' value='{{ mysql_root_password | quote }}' vtype='password'

#Install packages
- name: Install percona database server
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - percona-server-server-{{ db_version }}
    - percona-server-client-{{ db_version }}
    - python-mysqldb
  notify: restart percona server

# Update root password
- name: Set new root password
  mysql_user:
    check_implicit_admin=yes
    login_user=root
    login_password={{ mysql_root_password }}
    user=root
    password={{ mysql_root_password }}
    host={{ item }}
    priv='*.*:ALL,GRANT'
  with_items:
          - localhost
          - 127.0.0.1
          - "{{ ansible_hostname }}"
  notify: restart percona server

#Hardening
- name: Remove anonymous users
  mysql_user: name='' host={{ item }} state=absent login_user=root login_password={{ mysql_root_password }}
  with_items:
          - "{{ ansible_hostname }}"
          - localhost

- name: Remove test database
  mysql_db: name=test state=absent login_user=root login_password={{ mysql_root_password }}